language: python

python:
    - 2.7
    - 3.5
    - 3.6

matrix:
    include:
    - os: linux
    - os: osx
    
install:
    - pip install .

script:
    - python tests/1.py
    - python tests/2.py
    - python tests/3.py
